package com.ssxt.model;

// default package
// Generated 2016-1-15 15:31:32 by Hibernate Tools 4.3.1.Final

/**
 * Groups generated by hbm2java
 */
public class Groups implements java.io.Serializable {

	private Integer id;
	private String parent;
	private String name;
	private String code;
	private String parentId;

	public Groups() {
	}

	public Groups(String parent, String name, String code, String parentId) {
		this.parent = parent;
		this.name = name;
		this.code = code;
		this.parentId = parentId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getParent() {
		return this.parent;
	}

	public void setParent(String parent) {
		this.parent = parent;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

}
