package com.ssxt.model;
// default package
// Generated 2016-1-18 14:57:09 by Hibernate Tools 4.3.1.Final

/**
 * StType generated by hbm2java
 */
public class StcdType implements java.io.Serializable {
	private Integer id;
	private String type;
	private String typeName;

	public StcdType() {
	}

	public StcdType(String type, String typeName) {
		this.type = type;
		this.typeName = typeName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}
}