package com.ssxt.model;
// default package
// Generated 2016-2-4 14:25:02 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * StPptnRNew generated by hbm2java
 */
public class StPptnRNew implements java.io.Serializable {

	private Integer id;
	private String stcd;
	private String stmn;
	private String rvnm;
	private String bsnm;
	private String addvcd;
	private Date tm;	
//	private BigDecimal drp;
//	private BigDecimal intv;
	private BigDecimal pdr;
	private BigDecimal dyp;
	private Character wth;
	private Date addTime;

	public StPptnRNew() {
	}

	public StPptnRNew(String stcd, String stmn, String rvnm, String bsnm, String addvcd, Date tm, 
//			BigDecimal drp,
			BigDecimal intv, 
			BigDecimal pdr, 
			BigDecimal dyp, 
			Character wth, Date addTime) {
		this.stcd = stcd;
		this.stmn = stmn;
		this.rvnm = rvnm;
		this.bsnm = bsnm;
		this.addvcd = addvcd;
		this.tm = tm;
//		this.drp = drp;
//		this.intv = intv;
		this.pdr = pdr;
		this.dyp = dyp;
		this.wth = wth;
		this.addTime = addTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStcd() {
		return this.stcd;
	}

	public void setStcd(String stcd) {
		this.stcd = stcd;
	}

	public String getStmn() {
		return this.stmn;
	}

	public void setStmn(String stmn) {
		this.stmn = stmn;
	}

	public String getRvnm() {
		return this.rvnm;
	}

	public void setRvnm(String rvnm) {
		this.rvnm = rvnm;
	}

	public String getBsnm() {
		return this.bsnm;
	}

	public void setBsnm(String bsnm) {
		this.bsnm = bsnm;
	}

	public String getAddvcd() {
		return this.addvcd;
	}

	public void setAddvcd(String addvcd) {
		this.addvcd = addvcd;
	}

	public Date getTm() {
		return this.tm;
	}

	public void setTm(Date tm) {
		this.tm = tm;
	}

//	public BigDecimal getDrp() {
//		return this.drp;
//	}
//
//	public void setDrp(BigDecimal drp) {
//		this.drp = drp;
//	}

//	public BigDecimal getIntv() {
//		return this.intv;
//	}
//
//	public void setIntv(BigDecimal intv) {
//		this.intv = intv;
//	}

	public BigDecimal getPdr() {
		return this.pdr;
	}

	public void setPdr(BigDecimal pdr) {
		this.pdr = pdr;
	}

	public BigDecimal getDyp() {
		return this.dyp;
	}

	public void setDyp(BigDecimal dyp) {
		this.dyp = dyp;
	}

	public Character getWth() {
		return this.wth;
	}

	public void setWth(Character wth) {
		this.wth = wth;
	}

	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}
	
	private String tms;
	public String getTms() {
		if(tm!=null)
			return sdf.format(tm);
		return "1970-01-01 00:00:00";
	}
	private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");	

}
