package com.ssxt.model;
// default package
// Generated 2016-1-19 10:11:30 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * StPptnR generated by hbm2java
 */
public class StPptnR implements java.io.Serializable {

	private Integer id;
	private String stcd;
	private Date tm;
	private BigDecimal drp;
	private BigDecimal intv;
	private BigDecimal pdr;

	private BigDecimal dyp;
	private Character wth;

	public StPptnR() {
	}
	public StPptnR(Integer id, String stcd) {
		super();
		this.id = id;
		this.stcd = stcd;
	}

	public StPptnR(String stcd, Date tm, BigDecimal drp, BigDecimal intv, BigDecimal pdr, BigDecimal dyp,
			Character wth) {
		this.stcd = stcd;
		this.tm = tm;
		this.drp = drp;
		this.intv = intv;
		this.pdr = pdr;
		this.dyp = dyp;
		this.wth = wth;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStcd() {
		return this.stcd;
	}

	public void setStcd(String stcd) {
		this.stcd = stcd;
	}

	public Date getTm() {
		return this.tm;
	}

	public void setTm(Date tm) {
		this.tm = tm;
	}

	public BigDecimal getDrp() {
		return this.drp;
	}

	public void setDrp(BigDecimal drp) {
		this.drp = drp;
	}

	public BigDecimal getIntv() {
		return this.intv;
	}

	public void setIntv(BigDecimal intv) {
		this.intv = intv;
	}

	public BigDecimal getPdr() {
		return this.pdr;
	}

	public void setPdr(BigDecimal pdr) {
		this.pdr = pdr;
	}

	public BigDecimal getDyp() {
		return this.dyp;
	}

	public void setDyp(BigDecimal dyp) {
		this.dyp = dyp;
	}

	public Character getWth() {
		return this.wth;
	}

	public void setWth(Character wth) {
		this.wth = wth;
	}

}
