package com.ssxt.model;
// default package
// Generated 2016-2-22 14:50:58 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * StRiverR generated by hbm2java
 */
public class StRiverR implements java.io.Serializable {

	private Integer id;
	private String stcd;
	private Date tm;
	private BigDecimal z;
	private BigDecimal q;
	private String wptn;
	private BigDecimal xsa;
	private BigDecimal xsavv;
	private BigDecimal xsmxv;
	private String flwchrcd;
	private String msqmt;
	private String msamt;
	private String msvmt;
	private Date addTime;

	public StRiverR() {
	}

	public StRiverR(String stcd, Date tm, BigDecimal z, BigDecimal q, String wptn, BigDecimal xsa, BigDecimal xsavv,
			BigDecimal xsmxv, String flwchrcd, String msqmt, String msamt, String msvmt, Date addTime) {
		this.stcd = stcd;
		this.tm = tm;
		this.z = z;
		this.q = q;
		this.wptn = wptn;
		this.xsa = xsa;
		this.xsavv = xsavv;
		this.xsmxv = xsmxv;
		this.flwchrcd = flwchrcd;
		this.msqmt = msqmt;
		this.msamt = msamt;
		this.msvmt = msvmt;
		this.addTime = addTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStcd() {
		return this.stcd;
	}

	public void setStcd(String stcd) {
		this.stcd = stcd;
	}

	public Date getTm() {
		return this.tm;
	}

	public void setTm(Date tm) {
		this.tm = tm;
	}

	public BigDecimal getZ() {
		return this.z;
	}

	public void setZ(BigDecimal z) {
		this.z = z;
	}

	public BigDecimal getQ() {
		return this.q;
	}

	public void setQ(BigDecimal q) {
		this.q = q;
	}

	public String getWptn() {
		return this.wptn;
	}

	public void setWptn(String wptn) {
		this.wptn = wptn;
	}

	public BigDecimal getXsa() {
		return this.xsa;
	}

	public void setXsa(BigDecimal xsa) {
		this.xsa = xsa;
	}

	public BigDecimal getXsavv() {
		return this.xsavv;
	}

	public void setXsavv(BigDecimal xsavv) {
		this.xsavv = xsavv;
	}

	public BigDecimal getXsmxv() {
		return this.xsmxv;
	}

	public void setXsmxv(BigDecimal xsmxv) {
		this.xsmxv = xsmxv;
	}

	public String getFlwchrcd() {
		return this.flwchrcd;
	}

	public void setFlwchrcd(String flwchrcd) {
		this.flwchrcd = flwchrcd;
	}

	public String getMsqmt() {
		return this.msqmt;
	}

	public void setMsqmt(String msqmt) {
		this.msqmt = msqmt;
	}

	public String getMsamt() {
		return this.msamt;
	}

	public void setMsamt(String msamt) {
		this.msamt = msamt;
	}

	public String getMsvmt() {
		return this.msvmt;
	}

	public void setMsvmt(String msvmt) {
		this.msvmt = msvmt;
	}

	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}
	
	private String tms;
	public String getTms() {
		return sdf.format(tm);
	}
	private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

}
