package com.ssxt.model;

// default package
// Generated 2016-1-15 15:31:32 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * StStbprpB generated by hbm2java
 */
public class StStbprpB implements java.io.Serializable {

	private Integer id;
	private String stcd;
	private String stmn;
	private String rvnm;
	private String hnnm;
	private String bsnm;
	private BigDecimal lgtd;
	private BigDecimal lttd;
	private String stlc;
	private String addvcd;
	private String dtmnm;
	private BigDecimal dtmel;
	private String sttp;
	private String frgrd;
	private String bgfrym;
	private String admauth;
	private String stbk;
	private Integer drna;
	private BigDecimal dstrvm;
	private String usfl;
	private String phcd;
	private BigDecimal dtpr;
	private String esstym;
	private String atcunit;
	private String locality;
	private Long stazt;
	private String comments;
	private Date moditime;
	private String codeName;
	private Groups groups;
	private StcdType stcdtype;


//	public StStbprpB(String stcd, String stmn, String bsnm, String sttp, String codeName) {
//		super();
//		this.stcd = stcd;
//		this.stmn = stmn;
//		this.bsnm = bsnm;
//		this.sttp = sttp;
//		this.codeName = codeName;
//	}

	
	public StcdType getStcdtype() {
		return stcdtype;
	}




	public void setStcdtype(StcdType stcdtype) {
		this.stcdtype = stcdtype;
	}




	public StStbprpB(Integer id, Groups groups, StcdType stcdtype) {
		super();
		this.id = id;
		this.groups = groups;
		this.stcdtype = stcdtype;
	}

	
	
	
	public StStbprpB() {
		
	}

	public StStbprpB(String stcd, String stmn, String rvnm, String hnnm, String bsnm, BigDecimal lgtd, BigDecimal lttd,
			String stlc, String addvcd, String dtmnm, BigDecimal dtmel, String sttp, String frgrd, String bgfrym,
			String admauth, String stbk, Integer drna, BigDecimal dstrvm, String usfl, String phcd, BigDecimal dtpr,
			String esstym, String atcunit, String locality, Long stazt, String comments, Date moditime, Groups groups, StcdType stcdtype) {
		this.stcd = stcd;
		this.stmn = stmn;
		this.rvnm = rvnm;
		this.hnnm = hnnm;
		this.bsnm = bsnm;
		this.lgtd = lgtd;
		this.lttd = lttd;
		this.stlc = stlc;
		this.addvcd = addvcd;
		this.dtmnm = dtmnm;
		this.dtmel = dtmel;
		this.sttp = sttp;
		this.frgrd = frgrd;
		this.bgfrym = bgfrym;
		this.admauth = admauth;
		this.stbk = stbk;
		this.drna = drna;
		this.dstrvm = dstrvm;
		this.usfl = usfl;
		this.phcd = phcd;
		this.dtpr = dtpr;
		this.esstym = esstym;
		this.atcunit = atcunit;
		this.locality = locality;
		this.stazt = stazt;
		this.comments = comments;
		this.moditime = moditime;
//		this.groups = groups;
		this.stcdtype = stcdtype;
	}
	
	
	public Groups getGroups() {
		return groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	 
	public String getCodeName() {
		return codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStcd() {
		return this.stcd;
	}

	public void setStcd(String stcd) {
		this.stcd = stcd;
	}

	public String getStmn() {
		return this.stmn;
	}

	public void setStmn(String stmn) {
		this.stmn = stmn;
	}

	public String getRvnm() {
		return this.rvnm;
	}

	public void setRvnm(String rvnm) {
		this.rvnm = rvnm;
	}

	public String getHnnm() {
		return this.hnnm;
	}

	public void setHnnm(String hnnm) {
		this.hnnm = hnnm;
	}

	public String getBsnm() {
		return this.bsnm;
	}

	public void setBsnm(String bsnm) {
		this.bsnm = bsnm;
	}

	public BigDecimal getLgtd() {
		return this.lgtd;
	}

	public void setLgtd(BigDecimal lgtd) {
		this.lgtd = lgtd;
	}

	public BigDecimal getLttd() {
		return this.lttd;
	}

	public void setLttd(BigDecimal lttd) {
		this.lttd = lttd;
	}

	public String getStlc() {
		return this.stlc;
	}

	public void setStlc(String stlc) {
		this.stlc = stlc;
	}

	public String getAddvcd() {
		return this.addvcd;
	}

	public void setAddvcd(String addvcd) {
		this.addvcd = addvcd;
	}

	public String getDtmnm() {
		return this.dtmnm;
	}

	public void setDtmnm(String dtmnm) {
		this.dtmnm = dtmnm;
	}

	public BigDecimal getDtmel() {
		return this.dtmel;
	}

	public void setDtmel(BigDecimal dtmel) {
		this.dtmel = dtmel;
	}

	public String getSttp() {
		return this.sttp;
	}

	public void setSttp(String sttp) {
		this.sttp = sttp;
	}

	public String getFrgrd() {
		return this.frgrd;
	}

	public void setFrgrd(String frgrd) {
		this.frgrd = frgrd;
	}

	public String getBgfrym() {
		return this.bgfrym;
	}

	public void setBgfrym(String bgfrym) {
		this.bgfrym = bgfrym;
	}

	public String getAdmauth() {
		return this.admauth;
	}

	public void setAdmauth(String admauth) {
		this.admauth = admauth;
	}

	public String getStbk() {
		return this.stbk;
	}

	public void setStbk(String stbk) {
		this.stbk = stbk;
	}

	public Integer getDrna() {
		return this.drna;
	}

	public void setDrna(Integer drna) {
		this.drna = drna;
	}

	public BigDecimal getDstrvm() {
		return this.dstrvm;
	}

	public void setDstrvm(BigDecimal dstrvm) {
		this.dstrvm = dstrvm;
	}

	public String getUsfl() {
		return this.usfl;
	}

	public void setUsfl(String usfl) {
		this.usfl = usfl;
	}

	public String getPhcd() {
		return this.phcd;
	}

	public void setPhcd(String phcd) {
		this.phcd = phcd;
	}

	public BigDecimal getDtpr() {
		return this.dtpr;
	}

	public void setDtpr(BigDecimal dtpr) {
		this.dtpr = dtpr;
	}

	public String getEsstym() {
		return this.esstym;
	}

	public void setEsstym(String esstym) {
		this.esstym = esstym;
	}

	public String getAtcunit() {
		return this.atcunit;
	}

	public void setAtcunit(String atcunit) {
		this.atcunit = atcunit;
	}

	public String getLocality() {
		return this.locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	public Long getStazt() {
		return this.stazt;
	}

	public void setStazt(Long stazt) {
		this.stazt = stazt;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getModitime() {
		return this.moditime;
	}

	public void setModitime(Date moditime) {
		this.moditime = moditime;
	}

	private String tms;
	public String getTms() {
		if(moditime!=null)
			return sdf.format(moditime);
		return "1970-01-01 00:00:00";
	}
	private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
}
